{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'\\n\\n整體功能描述\\n\\n'"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "'''\n",
    "\n",
    "整體功能描述\n",
    "\n",
    "'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "\n",
    "Application 主架構\n",
    "\n",
    "'''\n",
    "import pymysql, time, redis, json\n",
    "from urllib.parse import parse_qs \n",
    "from liffpy import LineFrontendFramework as LIFF\n",
    "from flask import Flask, request, abort, render_template\n",
    "from flask_sqlalchemy import SQLAlchemy\n",
    "from linebot.models.template import *\n",
    "from linebot.models import *\n",
    "# 引用自定義python\n",
    "import transform, user_based_recommender\n",
    "\n",
    "# 從linebot 套件包裡引用 LineBotApi 與 WebhookHandler 類別\n",
    "from linebot import (\n",
    "    LineBotApi, WebhookHandler\n",
    ")\n",
    "\n",
    "# 引用無效簽章錯誤\n",
    "from linebot.exceptions import (\n",
    "    InvalidSignatureError\n",
    ")\n",
    "\n",
    "\n",
    "# 載入基礎設定檔\n",
    "secretFileContentJson=json.load(open(\"./line_secret_key\",'r',encoding='utf8'))\n",
    "server_url=secretFileContentJson.get(\"server_url\")\n",
    "\n",
    "# 設定Server啟用細節\n",
    "app = Flask(__name__,static_url_path = \"/素材\" , static_folder = \"./素材/\")\n",
    "\n",
    "# 生成實體物件\n",
    "line_bot_api = LineBotApi(secretFileContentJson.get(\"channel_access_token\"))\n",
    "handler = WebhookHandler(secretFileContentJson.get(\"secret_key\"))\n",
    "\n",
    "# liff\n",
    "line_bot_token = secretFileContentJson.get(\"channel_access_token\")\n",
    "liff = LIFF(line_bot_token)\n",
    "\n",
    "# 啟動server對外接口，使Line能丟消息進來\n",
    "@app.route(\"/\", methods=['POST'])\n",
    "def callback():\n",
    "    # get X-Line-Signature header value\n",
    "    signature = request.headers['X-Line-Signature']\n",
    "\n",
    "    # get request body as text\n",
    "    body = request.get_data(as_text=True)\n",
    "    app.logger.info(\"Request body: \" + body)\n",
    "\n",
    "    # handle webhook body\n",
    "    try:\n",
    "        handler.handle(body, signature)\n",
    "    except InvalidSignatureError:\n",
    "        abort(400)\n",
    "\n",
    "    return 'OK'\n",
    "\n",
    "# pymysql設定資料庫連線設定\n",
    "host = 'localhost'\n",
    "port = 3306\n",
    "user = 'root'\n",
    "passwd = 'root'\n",
    "db = 'storedb'\n",
    "\n",
    "# SQLAlchemy設定資料庫連線設定\n",
    "class Config(object):\n",
    "    '''配置參數'''\n",
    "    #　sqlalchemy的配置參數\n",
    "    SQLALCHEMY_DATABASE_URI = \"mysql://root:root@localhost:3306/storedb\"\n",
    "    #　設置是否sqlalchemy自動追蹤資料庫的修改並發送訊號\n",
    "    SQLALCHEMY_TRACK_MODIFICATIONS = False\n",
    "\n",
    "app.config.from_object(Config)\n",
    "\n",
    "# 創建資料庫sqlalchemy工具對象\n",
    "db2 = SQLAlchemy(app)\n",
    "\n",
    "# redis設定\n",
    "redis = redis.StrictRedis(host='192.168.1.24', port=6379, password='iii')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "\n",
    "消息判斷器\n",
    "\n",
    "讀取指定的json檔案後，把json解析成不同格式的SendMessage\n",
    "\n",
    "讀取檔案，\n",
    "把內容轉換成json\n",
    "將json轉換成消息\n",
    "放回array中，並把array傳出。\n",
    "\n",
    "'''\n",
    "\n",
    "def detect_json_array_to_new_message_array(fileName):\n",
    "    \n",
    "    #開啟檔案，轉成json\n",
    "    with open(fileName,'r',encoding='utf-8') as f:\n",
    "        jsonArray = json.load(f)\n",
    "    \n",
    "    # 解析json\n",
    "    returnArray = []\n",
    "    for jsonObject in jsonArray:\n",
    "\n",
    "        # 讀取其用來判斷的元件\n",
    "        message_type = jsonObject.get('type')\n",
    "        \n",
    "        # 轉換\n",
    "        if message_type == 'text':\n",
    "            returnArray.append(TextSendMessage.new_from_json_dict(jsonObject))\n",
    "        elif message_type == 'imagemap':\n",
    "            returnArray.append(ImagemapSendMessage.new_from_json_dict(jsonObject))\n",
    "        elif message_type == 'template':\n",
    "            returnArray.append(TemplateSendMessage.new_from_json_dict(jsonObject))\n",
    "        elif message_type == 'image':\n",
    "            returnArray.append(ImageSendMessage.new_from_json_dict(jsonObject))\n",
    "        elif message_type == 'sticker':\n",
    "            returnArray.append(StickerSendMessage.new_from_json_dict(jsonObject))  \n",
    "        elif message_type == 'audio':\n",
    "            returnArray.append(AudioSendMessage.new_from_json_dict(jsonObject))  \n",
    "        elif message_type == 'location':\n",
    "            returnArray.append(LocationSendMessage.new_from_json_dict(jsonObject))\n",
    "        elif message_type == 'flex':\n",
    "            returnArray.append(FlexSendMessage.new_from_json_dict(jsonObject))  \n",
    "        elif message_type == 'video':\n",
    "            returnArray.append(FlexSendMessage.new_from_json_dict(jsonObject))\n",
    "        elif message_type == 'bubble':\n",
    "            message_after = BubbleContainer.new_from_json_dict(jsonObject)\n",
    "            returnArray.append(FlexSendMessage(alt_text=\"hello2\", contents=message_after))   \n",
    "\n",
    "\n",
    "    # 回傳\n",
    "    return returnArray"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "\n",
    "handler處理關注消息\n",
    "\n",
    "用戶關注時，讀取 素材 -> 關注 -> reply.json\n",
    "\n",
    "將其轉換成可寄發的消息，傳回給Line\n",
    "\n",
    "'''\n",
    "\n",
    "# 關注事件處理\n",
    "@handler.add(FollowEvent)\n",
    "def process_follow_event(event):\n",
    "    \n",
    "    # 讀取並轉換\n",
    "    result_message_array =[]\n",
    "    replyJsonPath = \"素材/關注/reply.json\"\n",
    "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
    "    \n",
    "    # 消息發送\n",
    "    line_bot_api.reply_message(\n",
    "        event.reply_token,\n",
    "        result_message_array\n",
    "    )\n",
    "    \n",
    "    # 啟動第一張圖文選單\n",
    "    linkRichMenuId = open(\"素材/\"+'rich_menu_0'+'/rich_menu_id', 'r').read()\n",
    "    line_bot_api.link_rich_menu_to_user(event.source.user_id,linkRichMenuId)\n",
    "        \n",
    "    replyJsonPath = '素材/'+'rich_menu_0'+\"/reply.json\"\n",
    "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "\n",
    "handler處理文字消息\n",
    "\n",
    "收到用戶回應的文字消息，\n",
    "按文字消息內容，往素材資料夾中，找尋以該內容命名的資料夾，讀取裡面的reply.json\n",
    "\n",
    "轉譯json後，將消息回傳給用戶\n",
    "\n",
    "'''\n",
    "\n",
    "# 文字消息處理\n",
    "@handler.add(MessageEvent,message=TextMessage)\n",
    "def process_text_message(event):\n",
    "\n",
    "    # 讀取本地檔案，並轉譯成消息\n",
    "    result_message_array =[]\n",
    "    replyJsonPath = \"素材/\"+event.message.text+\"/reply.json\"\n",
    "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
    "\n",
    "    # 發送\n",
    "    line_bot_api.reply_message(\n",
    "        event.reply_token,\n",
    "        result_message_array\n",
    "    )\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "\n",
    "handler處理Postback Event\n",
    "\n",
    "載入功能選單與啟動特殊功能\n",
    "\n",
    "解析postback的data，並按照data欄位判斷處理\n",
    "\n",
    "現有三個欄位\n",
    "menu, folder, tag\n",
    "\n",
    "若folder欄位有值，則\n",
    "    讀取其reply.json，轉譯成消息，並發送\n",
    "\n",
    "若menu欄位有值，則\n",
    "    讀取其rich_menu_id，並取得用戶id，將用戶與選單綁定\n",
    "    讀取其reply.json，轉譯成消息，並發送\n",
    "\n",
    "'''\n",
    "\n",
    "@handler.add(PostbackEvent)\n",
    "def process_postback_event(event):\n",
    "    \n",
    "    query_string_dict = parse_qs(event.postback.data)\n",
    "    \n",
    "    print(query_string_dict)\n",
    "    if 'folder' in query_string_dict:\n",
    "    \n",
    "        result_message_array =[]\n",
    "\n",
    "        replyJsonPath = '素材/'+query_string_dict.get('folder')[0]+\"/reply.json\"\n",
    "        result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
    "  \n",
    "        line_bot_api.reply_message(\n",
    "            event.reply_token,\n",
    "            result_message_array\n",
    "        )\n",
    "    elif 'menu' in query_string_dict:\n",
    " \n",
    "        linkRichMenuId = open(\"素材/\"+query_string_dict.get('menu')[0]+'/rich_menu_id', 'r').read()\n",
    "        line_bot_api.link_rich_menu_to_user(event.source.user_id,linkRichMenuId)\n",
    "        \n",
    "        replyJsonPath = '素材/'+query_string_dict.get('menu')[0]+\"/reply.json\"\n",
    "        result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
    "  \n",
    "        line_bot_api.reply_message(\n",
    "            event.reply_token,\n",
    "            result_message_array\n",
    "        )\n",
    "    \n",
    "    # 取出用戶Line的userID及username並存到資料庫\n",
    "    elif 'menu2' in query_string_dict:\n",
    "        # 建立連線\n",
    "        conn = pymysql.connect(host=host, port=port, user=user, passwd=passwd, db=db)\n",
    "        # 建立游標\n",
    "        cursor = conn.cursor()  \n",
    "        \n",
    "        linkRichMenuId = open(\"素材/\"+query_string_dict.get('menu2')[0]+'/rich_menu_id', 'r').read()\n",
    "        line_bot_api.link_rich_menu_to_user(event.source.user_id,linkRichMenuId)        \n",
    "        \n",
    "        # 取出消息內User的資料\n",
    "        user_profile = line_bot_api.get_profile(event.source.user_id)\n",
    "        \n",
    "        # 將用戶資訊存在檔案內\n",
    "        with open(\"./users.txt\", \"a\") as myfile:\n",
    "            myfile.write(json.dumps(vars(user_profile),sort_keys=True))\n",
    "            myfile.write('\\n')\n",
    "        \n",
    "        try:\n",
    "            sql = '''\n",
    "            INSERT INTO user_info (userID, name,regionID)\n",
    "            VALUES ('{}','{}', 0);\n",
    "            '''.format(str(user_profile.user_id),str(user_profile.display_name))\n",
    "            \n",
    "            cursor.execute(sql)\n",
    "            conn.commit()\n",
    "        \n",
    "            line_bot_api.reply_message(\n",
    "                event.reply_token,\n",
    "                TextSendMessage(text=\"%s 您好!\\n您可以點擊'常見問題'來查詢如何使用吾人能購\" %(user_profile.display_name)))\n",
    "        \n",
    "        except pymysql.err.IntegrityError:\n",
    "            print('Error', user_profile.user_id, 'existed.')\n",
    "            line_bot_api.reply_message(\n",
    "                event.reply_token,\n",
    "                TextSendMessage(text=\"親愛的 %s 會員您好!\\n感謝您回來繼續使用我們的服務\" %(user_profile.display_name)))\n",
    "            \n",
    "        # 關閉游標及連線\n",
    "        cursor.close()\n",
    "        conn.close()\n",
    "        \n",
    "    # 從資料庫取出用戶的歷史交易紀錄五筆，並將詳細交易紀錄寫進網頁\n",
    "    elif 'history' in query_string_dict:\n",
    "        # 建立連線\n",
    "        conn = pymysql.connect(host=host, port=port, user=user, passwd=passwd, db=db)\n",
    "        # 建立游標\n",
    "        cursor = conn.cursor()    \n",
    "    \n",
    "        # 取出消息內User的資料\n",
    "        user_profile = line_bot_api.get_profile(event.source.user_id)\n",
    "        userID = str(user_profile.user_id)\n",
    "\n",
    "        # 刪除過多的liff\n",
    "        try:\n",
    "            if len(liff.get()) >= 5:\n",
    "                for i in range(len(liff.get())):\n",
    "                    liff.delete(liff.get()[i]['liffId'])\n",
    "        except:\n",
    "            pass\n",
    "\n",
    "        try:\n",
    "            @app.route('/detail/<userID>/<shoppingdate>' , methods=['GET'])\n",
    "            def detail(userID,shoppingdate):\n",
    "                \n",
    "                shoppingdate = int(shoppingdate)\n",
    "                shoppingdate = time.localtime(shoppingdate)\n",
    "                shoppingdate = time.strftime(\"%Y-%m-%d %H:%M:%S\", shoppingdate)\n",
    "                \n",
    "                sql = '''select p.productName,p.unitprice,s.quantity,p.unitprice*s.quantity as total \n",
    "                from shoppinglist s join product p\n",
    "                on s.productID = p.productID\n",
    "                where s.userID = '{}' and s.shoppingdate = '{}';'''.format(userID,shoppingdate)\n",
    "\n",
    "                content = db2.engine.execute(sql).fetchall()\n",
    "                content_num = len(content)\n",
    "                total = 0\n",
    "                for i in content:\n",
    "                    total += int(i[3])\n",
    "\n",
    "                return render_template('detail.html', content=content , total=total , content_num=content_num)\n",
    "        except:\n",
    "            pass\n",
    "        \n",
    "        sql = '''SELECT shoppingdate FROM shoppinglist \n",
    "        WHERE userID =  '{}' GROUP BY shoppingdate ORDER BY shoppingdate DESC LIMIT 5;\n",
    "        '''.format(userID)\n",
    "            \n",
    "        cursor.execute(sql)\n",
    "        data = cursor.fetchall()\n",
    "        \n",
    "        timestamp = []\n",
    "        for j in range(len(data)):\n",
    "            timestamp.append(int(time.mktime(time.strptime(str(data[j][0]),\"%Y-%m-%d %H:%M:%S\"))))\n",
    "        \n",
    "        # 產生liff網頁\n",
    "        url = []\n",
    "        liff_uri = []\n",
    "        for i in range(len(timestamp)):\n",
    "            url.append('{}'.format(server_url) + '/detail/' + '{}'.format(userID) + '/' + str(timestamp[i]))\n",
    "        for liffuri in url:\n",
    "            liff_uri.append('https://liff.line.me/' + liff.add(view_type=\"tall\",view_url=liffuri))\n",
    "\n",
    "        message_before = transform.transform_hist(data,liff_uri)\n",
    "        message_after = BubbleContainer.new_from_json_dict(json.loads(message_before))\n",
    "        message = FlexSendMessage(alt_text=\"hello2\", contents=message_after)\n",
    "        \n",
    "        line_bot_api.reply_message(\n",
    "            event.reply_token, \n",
    "            message)\n",
    "\n",
    "        # 關閉游標及連線\n",
    "        cursor.close()\n",
    "        conn.close()\n",
    "    \n",
    "    # 從資料庫取出用戶個人資料，並建立網頁供用戶修改資料，再存回資料庫\n",
    "    elif 'information' in query_string_dict:\n",
    "        # 建立連線\n",
    "        conn = pymysql.connect(host=host, port=port, user=user, passwd=passwd, db=db)\n",
    "        # 建立游標\n",
    "        cursor = conn.cursor()          \n",
    "\n",
    "        # 取出消息內User的資料\n",
    "        user_profile = line_bot_api.get_profile(event.source.user_id)\n",
    "        userID = str(user_profile.user_id)\n",
    "        \n",
    "        # 刪除過多的liff\n",
    "        try:\n",
    "            if len(liff.get()) >= 5:\n",
    "                for i in range(len(liff.get())):\n",
    "                    liff.delete(liff.get()[i]['liffId'])\n",
    "        except:\n",
    "            pass\n",
    "        \n",
    "        # 建立網頁並將修改完後的資料存回資料庫\n",
    "        try:\n",
    "            @app.route('/change/<userID>' , methods=['GET'])\n",
    "            def change(userID):\n",
    "                return render_template('change.html' , ID = userID)\n",
    "            @app.route('/submit', methods =['POST'])\n",
    "            def submit():\n",
    "                user_ID = request.values['user_ID']\n",
    "                name = request.values['name']\n",
    "                gender = request.values['gender']\n",
    "                regionID = request.values['regionID']\n",
    "\n",
    "                sql = '''UPDATE user_info \n",
    "                    SET name = '{}', gender = '{}', regionID = '{}'\n",
    "                    WHERE userID = '{}';'''.format(name,gender,regionID,user_ID)\n",
    "\n",
    "                db2.engine.execute(sql)\n",
    "\n",
    "                if gender == 'male':\n",
    "                    flask_gender = '男'\n",
    "                    \n",
    "                else:\n",
    "                    flask_gender = '女'\n",
    "                if regionID == '320':\n",
    "                    flask_region = '中壢區'\n",
    "                elif regionID == '324':\n",
    "                    flask_region = '平鎮區'\n",
    "                elif regionID == '325':\n",
    "                    flask_region = '龍潭區'\n",
    "                elif regionID == '326':\n",
    "                    flask_region = '楊梅區'\n",
    "                elif regionID == '327':\n",
    "                    flask_region = '新屋區'\n",
    "                elif regionID == '328':\n",
    "                    flask_region = '觀音區'\n",
    "                elif regionID == '330':\n",
    "                    flask_region = '桃園區'\n",
    "                elif regionID == '333':\n",
    "                    flask_region = '龜山區'\n",
    "                elif regionID == '334':\n",
    "                    flask_region = '八德區'\n",
    "                elif regionID == '335':\n",
    "                    flask_region = '大溪區'\n",
    "                elif regionID == '336':\n",
    "                    flask_region = '復興區'\n",
    "                elif regionID == '337':\n",
    "                    flask_region = '大園區'\n",
    "                elif regionID == '338':\n",
    "                    flask_region = '蘆竹區'\n",
    "                output = '''\n",
    "                <html>\n",
    "                    <head>\n",
    "                        <title>會員中心</title>\n",
    "                    </head>\n",
    "                    <body>\n",
    "                            <div>\n",
    "                                <font size=32 > <center> <b>您已將資料更改如下 </b> </center> </font>\n",
    "                            </div>\n",
    "                                <br>\n",
    "                            <div>\n",
    "                                <font size=32 > <center> 姓名: %s </center> </font>\n",
    "                            </div>\n",
    "                                <br>\n",
    "                            <div>\n",
    "                                <font size=32 > <center> 性別: %s </center> </font>\n",
    "                            </div>\n",
    "                                <br>\n",
    "                            <div>\n",
    "                                <font size=32 > <center> 地區: %s </center> </font>\n",
    "                            </div>\n",
    "                                <br>\n",
    "                    </body>\n",
    "                </html>\n",
    "                '''%(name,flask_gender,flask_region)\n",
    "\n",
    "                return output\n",
    "        except:\n",
    "            pass\n",
    "        \n",
    "        # 從資料庫取出用戶個人資料\n",
    "        sql = '''SELECT u.name,u.gender,r.regionName from user_info u join region r \n",
    "        on u.regionID = r.regionID where userID = \"{}\";'''.format(userID)\n",
    "        \n",
    "        cursor.execute(sql)\n",
    "\n",
    "        data = cursor.fetchmany(1)\n",
    "        data_name = str(data[0][0])\n",
    "        data_gender = str(data[0][1])\n",
    "        if data_gender == 'male':\n",
    "            data_gender = '男'\n",
    "        elif data_gender == 'female':\n",
    "            data_gender = '女'\n",
    "        data_gender = data_gender\n",
    "        data_regionID = str(data[0][2])\n",
    "\n",
    "        # 產生liff網頁\n",
    "        url = '{}'.format(server_url) + '/change/' + '{}'.format(userID)\n",
    "        liff_uri = 'https://liff.line.me/' + liff.add(view_type=\"tall\",view_url=url)\n",
    "        \n",
    "        \n",
    "        message_before = transform.transform_info(data_name,data_gender,data_regionID,liff_uri)\n",
    "        message_after = BubbleContainer.new_from_json_dict(json.loads(message_before))\n",
    "        message = FlexSendMessage(alt_text=\"hello\", contents=message_after)\n",
    "        line_bot_api.reply_message(\n",
    "            event.reply_token, \n",
    "            message)\n",
    "    \n",
    "    \n",
    "        # 關閉游標及連線\n",
    "        cursor.close()\n",
    "        conn.close()\n",
    "    \n",
    "    # 將暫時交易紀錄寫進網頁\n",
    "    elif 'shopping_cart' in query_string_dict:\n",
    "\n",
    "        # 取出消息內User的資料\n",
    "        user_profile = line_bot_api.get_profile(event.source.user_id)\n",
    "        userID = str(user_profile.user_id)\n",
    "\n",
    "        # 刪除過多的liff\n",
    "        try:\n",
    "            if len(liff.get()) >= 5:\n",
    "                for i in range(len(liff.get())):\n",
    "                    liff.delete(liff.get()[i]['liffId'])\n",
    "        except:\n",
    "            pass\n",
    "        \n",
    "        try:\n",
    "            @app.route('/shopcar/<userID>' , methods=['GET'])\n",
    "            def shopcar(userID):\n",
    "                try:\n",
    "                    redis_get = redis.get('{}'.format(userID))\n",
    "                    content = redis_get.decode('utf-8').split(',')\n",
    "                    content_num = len(content) \n",
    "                    total = 0\n",
    "                    for i in content:\n",
    "                        total += int(i.split(':')[3])\n",
    "                \n",
    "                    return render_template('shopcar.html', content=content, total=total, content_num=content_num)\n",
    "                except:\n",
    "                    total = 0\n",
    "                    return render_template('shopcar_empty.html', total=total)\n",
    "        except:\n",
    "            pass\n",
    "        \n",
    "        # 產生liff網頁\n",
    "        url = '{}'.format(server_url) + '/shopcar/' + '{}'.format(userID)\n",
    "        liff_uri = 'https://liff.line.me/' + liff.add(view_type=\"tall\",view_url=url)\n",
    "        \n",
    "        message_before = transform.transform_shopcar(liff_uri)\n",
    "        message_after = BubbleContainer.new_from_json_dict(json.loads(message_before))\n",
    "        message = FlexSendMessage(alt_text=\"hello3\", contents=message_after)\n",
    "        line_bot_api.reply_message(\n",
    "            event.reply_token, \n",
    "            message)\n",
    "        \n",
    "    # 推薦商品 \n",
    "    elif 'recommender' in query_string_dict:\n",
    "\n",
    "        # 建立連線\n",
    "        conn = pymysql.connect(host=host, port=port, user=user, passwd=passwd, db=db)\n",
    "        # 建立游標\n",
    "        cursor = conn.cursor()  \n",
    "\n",
    "        # 取出消息內User的資料\n",
    "        user_profile = line_bot_api.get_profile(event.source.user_id)\n",
    "        userID = str(user_profile.user_id)\n",
    "        \n",
    "        price = []\n",
    "        data = user_based_recommender.main('1') # userID\n",
    "        for i in data:\n",
    "            sql = '''select unitprice from product where productName ='{}';'''.format(i)\n",
    "            cursor.execute(sql)\n",
    "            i_price = cursor.fetchall()[0][0]\n",
    "            price.append(i_price)\n",
    "        \n",
    "        print(data)\n",
    "        print(price)\n",
    "        message_before = transform.transform_recom(data,price)\n",
    "        message_after = CarouselContainer.new_from_json_dict(json.loads(message_before))\n",
    "        message = FlexSendMessage(alt_text=\"oh\", contents=message_after)\n",
    "        line_bot_api.reply_message(\n",
    "            event.reply_token, \n",
    "            message)\n",
    "\n",
    "        # 關閉游標及連線\n",
    "        cursor.close()\n",
    "        conn.close()\n",
    "\n",
    "    # 常見問題\n",
    "    elif 'question' in query_string_dict:\n",
    "\n",
    "        # 創建QuickReplyButton \n",
    "        # 點擊後，以Postback事件回應Server \n",
    "        shopcarButton = QuickReplyButton(\n",
    "            action=PostbackAction(label=\"購物車\", data=\"folder=problem_shopcar\")\n",
    "        )\n",
    "        recomButton = QuickReplyButton(\n",
    "            action=PostbackAction(label=\"推薦商品\", data=\"folder=problem_recom\")\n",
    "        )\n",
    "        histButton = QuickReplyButton(\n",
    "            action=PostbackAction(label=\"交易紀錄\", data=\"folder=problem_hist\")\n",
    "        )\n",
    "        discountButton = QuickReplyButton(\n",
    "            action=PostbackAction(label=\"最新優惠\", data=\"folder=problem_discount\")\n",
    "        )\n",
    "        infoButton = QuickReplyButton(\n",
    "            action=PostbackAction(label=\"會員中心\", data=\"folder=problem_info\")\n",
    "        )\n",
    "        # 設計QuickReplyButton的List\n",
    "        quickReplyList = QuickReply(\n",
    "            items = [shopcarButton, recomButton, histButton, discountButton, infoButton]\n",
    "        )\n",
    "\n",
    "        line_bot_api.reply_message(\n",
    "            event.reply_token,\n",
    "            TextSendMessage(text='想問甚麼功能?', quick_reply=quickReplyList))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "\n",
    "若收到圖片消息時，\n",
    "\n",
    "先回覆用戶文字消息，並從Line上將照片拿回。\n",
    "\n",
    "'''\n",
    "\n",
    "message_before = transform.transform_start()\n",
    "message_after = BubbleContainer.new_from_json_dict(json.loads(message_before))\n",
    "message = FlexSendMessage(alt_text=\"haha\", contents=message_after)\n",
    "            \n",
    "@handler.add(MessageEvent, message=ImageMessage)\n",
    "def handle_message(event):\n",
    "    \n",
    "    line_bot_api.reply_message(\n",
    "        event.reply_token,\n",
    "        message)\n",
    "    message_content = line_bot_api.get_message_content(event.message.id)\n",
    "    with open('./素材/images/'+event.message.id+'.jpg', 'wb') as fd:\n",
    "        for chunk in message_content.iter_content():\n",
    "            fd.write(chunk)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 成功辨識出人臉後，向該會員傳送歡迎訊息\n",
    "@app.route(\"/welcome/<userID>\", methods=['GET'])\n",
    "def pushWelcom(userID):\n",
    "    try:\n",
    "        line_bot_api.push_message(userID, \n",
    "                                  [\n",
    "                                      TextSendMessage(text=\"歡迎光臨無人能購!\\n點擊'購物車'來查看本次交易的即時購買情形\\n祝您購物愉快!\"),\n",
    "                                  ]\n",
    "                                 )\n",
    "    except :\n",
    "        print('Push Error.')\n",
    "\n",
    "# 結束交易後，向該會員傳送交易結束訊息\n",
    "@app.route(\"/thank/<userID>\", methods=['GET'])\n",
    "def pushthank(userID):\n",
    "    try:\n",
    "        line_bot_api.push_message(userID, \n",
    "                                  [\n",
    "                                      TextSendMessage(text=\"感謝您的光臨!\\n點擊'交易紀錄'來查看最新紀錄\"),\n",
    "                                  ]\n",
    "                                 )\n",
    "    except :\n",
    "        print('Push Error.')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'recommender': ['123']}\n",
      "['三好米ㄧ等壽司米(圓一)2.7kg', '農心醡醬風味麵(包)140g', 'St.Michel巧克力奶油餅-150g', '英國Barr覆盆子風味無糖飲料-330ml', 'PMU熊寶貝 素色舒柔墊9入-淺藍 32*32*1cm']\n",
      "[278, 134, 128, 28, 179]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:02:17] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:02:17,765] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我想看推薦商品/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:02:17] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:03:18] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:03:18,463] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:03:18] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:03:22] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:03:28] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:04:14] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:07:00] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:07:01,064] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:07:01] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:07:04] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:07:24] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:07:40] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:07:46] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:10:31] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:10:33,009] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-4-0268630cac24>\", line 31, in process_follow_event\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/rich_menu_0/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:10:33] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-10-30 14:10:48,871] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我要加入會員/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:10:48] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:10:50] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n",
      "{'folder': ['上傳照片']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:10:50] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:10:51,361] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:10:51] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:10:52] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:10:58] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:10:58] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'menu2': ['rich_menu_1']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:11:00] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:11:01,196] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/啟動服務/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:11:01] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:11:05] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:11:11] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:11:14] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:11:15,099] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:11:15] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:11:17] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:11:51,626] ERROR in app: Exception on /welcome/U9e792af911a1f1cdf2e1fd5d46f676d7 [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1953, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1968, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2098, in make_response\n",
      "    \"The view function did not return a valid response. The\"\n",
      "TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Oct/2020 14:11:51] \"\u001b[35m\u001b[1mGET /welcome/U9e792af911a1f1cdf2e1fd5d46f676d7 HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:11:57] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:12:36,925] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:12:36] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:12:38] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:12:43] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:12:48] \"\u001b[37mGET /shopcar/U9e792af911a1f1cdf2e1fd5d46f676d7 HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:12:49] \"\u001b[33mGET /favicon.ico HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:12:49] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:12:54] \"\u001b[37mGET /shopcar/U9e792af911a1f1cdf2e1fd5d46f676d7 HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:12:56] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:13:00] \"\u001b[37mGET /shopcar/U9e792af911a1f1cdf2e1fd5d46f676d7 HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:13:07] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:13:13] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:13:19] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:13:25] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:13:32] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:13:38] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:13:43] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:13:49] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:13:55] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:14:01] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:14:07] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:14:13] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:14:20] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:14:25] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:14:31] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:14:37] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:14:44] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:14:50] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:14:56] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:15:02] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:15:08] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:15:14] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:15:20] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:15:26] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:15:32] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:15:38] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:15:44] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:15:50] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:15:56] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:16:02] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:16:06] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:16:12] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'recommender': ['123']}\n",
      "['三好米ㄧ等壽司米(圓一)2.7kg', '農心醡醬風味麵(包)140g', 'St.Michel巧克力奶油餅-150g', '英國Barr覆盆子風味無糖飲料-330ml', 'PMU熊寶貝 素色舒柔墊9入-淺藍 32*32*1cm']\n",
      "[278, 134, 128, 28, 179]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:18:48] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:18:48,861] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我想看推薦商品/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:18:48] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:18:50] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:18:51,369] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:18:51] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:18:52] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:18:54] \"\u001b[33mGET /favicon.ico HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:18:59] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:19:00] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:19:01,261] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:19:01] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:19:02] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:19:05] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:19:11] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:19:18] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:19:19] \"\u001b[33mGET /favicon.ico HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:19:24] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:19:31] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:19:37] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:19:43] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:19:49] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:19:55] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:20:01] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:20:07] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:20:13] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:20:19] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:20:27] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:20:37] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:20:43] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:20:56] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:20:56,159] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:20:56] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:20:56] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:20:56] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:21:02] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:21:07] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:21:14] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:21:20] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:21:26] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:21:32] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:21:49] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:22:16] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:22:40] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:22:57] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:23:12] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:23:27] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:23:42] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:24:07] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:24:18] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:24:24] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:24:41] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:24:51] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:28:51] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:29:37,351] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-4-0268630cac24>\", line 31, in process_follow_event\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/rich_menu_0/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:29:37] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-10-30 14:31:24,035] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我要加入會員/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:31:24] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:31:25] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'folder': ['上傳照片']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:31:37] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'menu2': ['rich_menu_1']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:31:40] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error Ue092fe8c3805d385eaed29c2aad6778c existed.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2020-10-30 14:31:41,565] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/啟動服務/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:31:41] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'recommender': ['123']}\n",
      "['三好米ㄧ等壽司米(圓一)2.7kg', '農心醡醬風味麵(包)140g', 'St.Michel巧克力奶油餅-150g', '英國Barr覆盆子風味無糖飲料-330ml', 'PMU熊寶貝 素色舒柔墊9入-淺藍 32*32*1cm']\n",
      "[278, 134, 128, 28, 179]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:31:53] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:31:53,763] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我想看推薦商品/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:31:53] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'recommender': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:36:34] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['三好米ㄧ等壽司米(圓一)2.7kg', '農心醡醬風味麵(包)140g', 'St.Michel巧克力奶油餅-150g', '英國Barr覆盆子風味無糖飲料-330ml', 'PMU熊寶貝 素色舒柔墊9入-淺藍 32*32*1cm']\n",
      "[278, 134, 128, 28, 179]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2020-10-30 14:36:34,162] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我想看推薦商品/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:36:34] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:39:14] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:40:13,808] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-4-0268630cac24>\", line 31, in process_follow_event\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/rich_menu_0/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:40:13] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:45:11] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'folder': ['上傳照片']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2020-10-30 14:45:12,967] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我要加入會員/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:45:12] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:45:21] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'menu2': ['rich_menu_1']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:45:23] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:45:24,567] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/啟動服務/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:45:24] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-10-30 14:46:07,007] ERROR in app: Exception on /welcome/Ue092fe8c3805d385eaed29c2aad6778c [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1953, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1968, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2098, in make_response\n",
      "    \"The view function did not return a valid response. The\"\n",
      "TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Oct/2020 14:46:07] \"\u001b[35m\u001b[1mGET /welcome/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-10-30 14:46:32,213] ERROR in app: Exception on /welcome/Ue092fe8c3805d385eaed29c2aad6778c [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1953, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1968, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2098, in make_response\n",
      "    \"The view function did not return a valid response. The\"\n",
      "TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Oct/2020 14:46:32] \"\u001b[35m\u001b[1mGET /welcome/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:46:50] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:46:50,863] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:46:50] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:46:52] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:47:17] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:47:18,469] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:47:18] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:47:20] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'history': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:47:40] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:47:40,570] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我想看前五筆交易紀錄/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:47:40] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:50:14] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:50:15,515] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-4-0268630cac24>\", line 31, in process_follow_event\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/rich_menu_0/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:50:15] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:50:25] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'folder': ['上傳照片']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2020-10-30 14:50:26,466] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我要加入會員/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:50:26] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:50:32] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'menu2': ['rich_menu_1']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:50:35] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:50:35,965] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/啟動服務/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:50:35] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-10-30 14:50:37,303] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:50:37] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:50:39] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:50:41] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:50:42] \"\u001b[33mGET /favicon.ico HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:50:47] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:50:53] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:50:59] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:51:05] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:51:12] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:51:18] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:51:24] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:51:30] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:51:33,627] ERROR in app: Exception on /welcome/Ub52d90a6b2c9b05bed228af9d7538a6b [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1953, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1968, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2098, in make_response\n",
      "    \"The view function did not return a valid response. The\"\n",
      "TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Oct/2020 14:51:33] \"\u001b[35m\u001b[1mGET /welcome/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-10-30 14:51:47,677] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:51:47] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:51:48] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:51:51] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:51:52] \"\u001b[33mGET /favicon.ico HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:51:57] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:52:03] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:52:09] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:52:15] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:52:21] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:52:27] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:52:33] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:52:39] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:52:45] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:52:51] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:53:06] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:53:35] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:53:53] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:54:18] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:54:52] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:55:09] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:55:19] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 14:55:30] \"\u001b[37mGET /shopcar/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'history': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 14:55:38] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 14:55:38,766] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我想看前五筆交易紀錄/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 14:55:38] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'history': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2020-10-30 15:02:46,167] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我想看前五筆交易紀錄/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:02:46] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:02:46] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:03:17,123] ERROR in app: Exception on /thank/Ub52d90a6b2c9b05bed228af9d7538a6b [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1953, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1968, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2098, in make_response\n",
      "    \"The view function did not return a valid response. The\"\n",
      "TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Oct/2020 15:03:17] \"\u001b[35m\u001b[1mGET /thank/Ub52d90a6b2c9b05bed228af9d7538a6b HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'history': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:03:20] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:03:21,767] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我想看前五筆交易紀錄/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:03:21] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:03:23] \"\u001b[37mGET /detail/Ub52d90a6b2c9b05bed228af9d7538a6b/1604041390 HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:03:24] \"\u001b[33mGET /favicon.ico HTTP/1.1\u001b[0m\" 404 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:04:35] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:04:35,666] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:04:35] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:08:18] \"\u001b[37mGET /detail/Ub52d90a6b2c9b05bed228af9d7538a6b/1604041390 HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:08:19] \"\u001b[33mGET /favicon.ico HTTP/1.1\u001b[0m\" 404 -\n",
      "[2020-10-30 15:09:10,020] ERROR in app: Exception on /welcome/Ue092fe8c3805d385eaed29c2aad6778c [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1953, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1968, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2098, in make_response\n",
      "    \"The view function did not return a valid response. The\"\n",
      "TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Oct/2020 15:09:10] \"\u001b[35m\u001b[1mGET /welcome/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:09:27] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:09:27,865] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:09:27] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:09:30] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:09:36] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:09:52] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:09:53,666] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:09:53] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:09:55] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:10:11,863] ERROR in app: Exception on /thank/Ue092fe8c3805d385eaed29c2aad6778c [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1953, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1968, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2098, in make_response\n",
      "    \"The view function did not return a valid response. The\"\n",
      "TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Oct/2020 15:10:11] \"\u001b[35m\u001b[1mGET /thank/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-10-30 15:10:16,367] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我想看前五筆交易紀錄/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:10:16] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'history': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:10:19] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:10:24] \"\u001b[37mGET /detail/Ue092fe8c3805d385eaed29c2aad6778c/1604041809 HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:13:10,575] ERROR in app: Exception on /welcome/Ue092fe8c3805d385eaed29c2aad6778c [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1953, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1968, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2098, in make_response\n",
      "    \"The view function did not return a valid response. The\"\n",
      "TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Oct/2020 15:13:10] \"\u001b[35m\u001b[1mGET /welcome/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-10-30 15:13:51,856] ERROR in app: Exception on /welcome/Ue092fe8c3805d385eaed29c2aad6778c [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1953, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1968, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2098, in make_response\n",
      "    \"The view function did not return a valid response. The\"\n",
      "TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Oct/2020 15:13:51] \"\u001b[35m\u001b[1mGET /welcome/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:14:06] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:14:07,568] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:14:07] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:14:10] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:14:15] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:14:22] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:14:28] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:14:34] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:14:41,335] ERROR in app: Exception on /thank/Ue092fe8c3805d385eaed29c2aad6778c [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1953, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1968, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2098, in make_response\n",
      "    \"The view function did not return a valid response. The\"\n",
      "TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Oct/2020 15:14:41] \"\u001b[35m\u001b[1mGET /thank/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'history': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:14:46] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:14:47,364] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我想看前五筆交易紀錄/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:14:47] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:14:50] \"\u001b[37mGET /detail/Ue092fe8c3805d385eaed29c2aad6778c/1604041809 HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:19:05,382] ERROR in app: Exception on /welcome/Ue092fe8c3805d385eaed29c2aad6778c [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1953, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1968, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2098, in make_response\n",
      "    \"The view function did not return a valid response. The\"\n",
      "TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Oct/2020 15:19:05] \"\u001b[35m\u001b[1mGET /welcome/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:19:21] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:19:21,964] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:19:21] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:19:24] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:19:30] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:19:36] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:19:42] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:19:48] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:19:54] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:19:56,989] ERROR in app: Exception on /thank/Ue092fe8c3805d385eaed29c2aad6778c [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1953, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1968, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2098, in make_response\n",
      "    \"The view function did not return a valid response. The\"\n",
      "TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Oct/2020 15:19:56] \"\u001b[35m\u001b[1mGET /thank/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'history': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:19:59] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:20:00,768] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我想看前五筆交易紀錄/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:20:00] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:20:03] \"\u001b[37mGET /detail/Ue092fe8c3805d385eaed29c2aad6778c/1604042394 HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:22:54,755] ERROR in app: Exception on /welcome/Ue092fe8c3805d385eaed29c2aad6778c [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1953, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1968, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2098, in make_response\n",
      "    \"The view function did not return a valid response. The\"\n",
      "TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Oct/2020 15:22:54] \"\u001b[35m\u001b[1mGET /welcome/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:23:10] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:23:10,867] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:23:10] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:23:12] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:23:18] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:23:24] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:23:30] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:23:36] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:23:41,492] ERROR in app: Exception on /thank/Ue092fe8c3805d385eaed29c2aad6778c [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1953, in full_dispatch_request\n",
      "    return self.finalize_request(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1968, in finalize_request\n",
      "    response = self.make_response(rv)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2098, in make_response\n",
      "    \"The view function did not return a valid response. The\"\n",
      "TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.\n",
      "127.0.0.1 - - [30/Oct/2020 15:23:41] \"\u001b[35m\u001b[1mGET /thank/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'history': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:23:45] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:23:46,633] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我想看前五筆交易紀錄/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:23:46] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:23:50] \"\u001b[37mGET /detail/Ue092fe8c3805d385eaed29c2aad6778c/1604042618 HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:31:13] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:31:14,326] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:31:14] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:31:16] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:31:22] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:31:28] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:31:40] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:31:46] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:31:52] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:31:58] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:32:04] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:32:10] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:32:16] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:32:22] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:32:28] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:32:34] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:32:40] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:32:46] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:32:52] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:32:58] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:33:04] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:33:11] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:33:17] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:33:23] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:33:29] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:35:24] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:35:25,105] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:35:25] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'history': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:37:43] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:37:44,421] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我想看前五筆交易紀錄/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:37:44] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:37:46] \"\u001b[37mGET /detail/Ue092fe8c3805d385eaed29c2aad6778c/1604042618 HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:38:22] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:38:23,515] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:38:23] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-10-30 15:38:45,766] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我想看前五筆交易紀錄/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:38:45] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'history': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:38:48] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:38:50] \"\u001b[37mGET /detail/Ue092fe8c3805d385eaed29c2aad6778c/1604042618 HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:39:04] \"\u001b[37mGET /detail/Ue092fe8c3805d385eaed29c2aad6778c/1604042618 HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:39:51] \"\u001b[37mGET /detail/Ue092fe8c3805d385eaed29c2aad6778c/1604042618 HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:41:01,410] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/即時購物車/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:41:01] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'shopping_cart': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:41:03] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:41:05] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:41:11] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:41:17] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:41:23] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:41:29] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [30/Oct/2020 15:41:35] \"\u001b[37mGET /shopcar/Ue092fe8c3805d385eaed29c2aad6778c HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'history': ['123']}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [30/Oct/2020 15:41:54] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-10-30 15:41:55,439] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-cd91b178c817>\", line 54, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 256, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"c:\\users\\big data\\anaconda3\\envs\\flask\\lib\\site-packages\\linebot\\webhook.py\", line 268, in __invoke_func\n",
      "    func(event)\n",
      "  File \"<ipython-input-5-ba957f820d2e>\", line 19, in process_text_message\n",
      "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
      "  File \"<ipython-input-3-0f8d99618d74>\", line 17, in detect_json_array_to_new_message_array\n",
      "    with open(fileName,'r',encoding='utf-8') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '素材/我想看前五筆交易紀錄/reply.json'\n",
      "127.0.0.1 - - [30/Oct/2020 15:41:55] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "'''\n",
    "\n",
    "Application 運行（開發版）\n",
    "\n",
    "'''\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(host='0.0.0.0')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'\\n\\nApplication 運行（heroku版）\\n\\n'"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "'''\n",
    "\n",
    "Application 運行（heroku版）\n",
    "\n",
    "'''\n",
    "\n",
    "# import os\n",
    "# if __name__ == \"__main__\":\n",
    "#     app.run(host='0.0.0.0',port=os.environ['PORT'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
